apiVersion: security.gardener.cloud/v1alpha1
kind: CredentialsBinding
metadata:
  name: NAMEPLACEHOLDER
  namespace: NAMESPACEPLACEHOLDER
credentialsRef:
  apiVersion: v1
  kind: Secret
  name: NAMEPLACEHOLDER
  namespace: NAMESPACEPLACEHOLDER
provider:
  type: PROVIDERPLACEHOLDER
