apiVersion: v1
kind: Secret
metadata:
  labels:
    provider.shoot.gardener.cloud/alicloud: "true"
    reference.gardener.cloud/credentialsbinding: "true"
  name: NAMEPLACEHOLDER
  namespace: NAMESPACEPLACEHOLDER
stringData:
  accessKeyID: dummy-access-key-id
  accessKeySecret: dummy-access-key-secret
type: Opaque
