apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: aws-secret
  namespace: NAMESPACEPLACEHOLDER
provider:
  type: aws
secretRef:
  name: aws-secret
  namespace: NAMESPACEPLACEHOLDER