apiVersion: v1
kind: Secret
metadata:
  labels:
    provider.shoot.gardener.cloud/azure: "true"
    reference.gardener.cloud/credentialsbinding: "true"
  name: NAMEPLACEHOLDER
  namespace: NAMESPACEPLACEHOLDER
stringData:
  clientID: 00000000-0000-0000-0000-000000000001
  clientSecret: dummy-client-secret
  subscriptionID: 00000000-0000-0000-0000-000000000002
  tenantID: 00000000-0000-0000-0000-000000000003
type: Opaque
