apiVersion: v1
kind: Secret
metadata:
  labels:
    provider.shoot.gardener.cloud/aws: "true"
    reference.gardener.cloud/credentialsbinding: "true"
  name: NAMEPLACEHOLDER
  namespace: NAMESPACEPLACEHOLDER
stringData:
  AWS_REGION: ""
  accessKeyID: dummy-access-key-id
  secretAccessKey: dummy-secret-access-key
type: Opaque
