apiVersion: v1
kind: Secret
metadata:
  labels:
    provider.shoot.gardener.cloud/openstack: "true"
    reference.gardener.cloud/credentialsbinding: "true"
  name: NAMEPLACEHOLDER
  namespace: NAMESPACEPLACEHOLDER
stringData:
  domainName: dummy-domain
  password: dummy-password
  tenantName: dummy-tenant
  username: dummy-user
type: Opaque
