apiVersion: v1
kind: Secret
metadata:
  labels:
    provider.shoot.gardener.cloud/gcp: "true"
    reference.gardener.cloud/credentialsbinding: "true"
  name: NAMEPLACEHOLDER
  namespace: NAMESPACEPLACEHOLDER
stringData:
  serviceaccount.json: '{"type":"service_account","project_id":"dummy-project"}'
type: Opaque
