apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  name: openstack-seed
spec:
  provider:
    type: openstack
    region: europe-1
    zones:
    - europe-1a
    - europe-1b
    - europe-1c
  dns:
    provider:
      type: openstack-designate
      secretRef:
        name: ingress-secret
        namespace: garden
  networks:
    ipFamilies:
    - IPv4
    nodes: 10.240.0.0/16
    pods: 10.241.128.0/17
    services: 10.241.0.0/17
  settings:
    scheduling:
      visible: true
