apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  name: soil
spec:
  provider:
    type: aws
    region: us-east-1
    zones:
    - us-east-1a
    - us-east-1b
  dns:
    provider:
      type: aws-route53
      secretRef:
        name: ingress-secret
        namespace: garden
  networks:
    ipFamilies:
    - IPv4
    nodes: 10.240.0.0/16
    pods: 10.241.128.0/17
    services: 10.241.0.0/17
    shootDefaults:
      pods: 100.64.0.0/12
      services: 100.104.0.0/13
  settings:
    scheduling:
      visible: true
