apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  name: aws
spec:
  provider:
    type: aws
    region: europe-1
    zones:
    - europe-1a
  dns:
    provider:
      type: aws-route53
      secretRef:
        name: ingress-secret
        namespace: garden
  networks:
    ipFamilies:
    - IPv4
    nodes: 10.240.0.0/16
    pods: 10.241.128.0/17
    services: 10.241.0.0/17
    shootDefaults:
      pods: 100.64.0.0/12
      services: 100.104.0.0/13
  accessRestrictions:
    - name: eu-access-only
  ingress:
    controller:
      kind: nginx
      providerConfig:
        use-proxy-protocol: true
    domain: ingress.aws.seed.fake.example.com
  settings:
    scheduling:
      visible: true