apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: backupbuckets.core.gardener.cloud
spec:
  conversion:
    strategy: None
  group: core.gardener.cloud
  names:
    categories:
    - all
    kind: BackupBucket
    listKind: BackupBucketList
    plural: backupbuckets
    shortNames:
    - bbc
    singular: backupbucket
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: BackupBucket holds details about backup bucket
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Specification of the Backup Bucket.
            properties:
              provider:
                description: Provider holds the details of cloud provider of the object
                  store. This field is immutable.
                properties:
                  region:
                    description: Region is the region of the bucket.
                    type: string
                  type:
                    description: Type is the type of provider.
                    type: string
                required:
                - type
                - region
                type: object
              providerConfig:
                description: ProviderConfig is the configuration passed to BackupBucket
                  resource.
                type: object
              secretRef:
                description: SecretRef is a reference to a secret that contains the
                  credentials to access object store.
                properties:
                  name:
                    description: name is unique within a namespace to reference a
                      secret resource.
                    type: string
                  namespace:
                    description: namespace defines the space within which the secret
                      name must be unique.
                    type: string
                type: object
              seedName:
                description: SeedName holds the name of the seed allocated to BackupBucket
                  for running controller. This field is immutable.
                type: string
            required:
            - provider
            - secretRef
            type: object
          status:
            description: Most recently observed status of the Backup Bucket.
            properties:
              generatedSecretRef:
                description: GeneratedSecretRef is reference to the secret generated
                  by backup bucket, which will have object store specific credentials.
                properties:
                  name:
                    description: name is unique within a namespace to reference a
                      secret resource.
                    type: string
                  namespace:
                    description: namespace defines the space within which the secret
                      name must be unique.
                    type: string
                type: object
              lastError:
                description: LastError holds information about the last occurred error
                  during an operation.
                properties:
                  codes:
                    description: Well-defined error codes of the last error(s).
                    items:
                      type: string
                    type: array
                  description:
                    description: A human readable message indicating details about
                      the last error.
                    type: string
                  lastUpdateTime:
                    description: Last time the error was reported
                    format: date-time
                    type: string
                  taskID:
                    description: ID of the task which caused this last error
                    type: string
                required:
                - description
                type: object
              lastOperation:
                description: LastOperation holds information about the last operation
                  on the BackupBucket.
                properties:
                  description:
                    description: A human readable message indicating details about
                      the last operation.
                    type: string
                  lastUpdateTime:
                    description: Last time the operation state transitioned from one
                      to another.
                    format: date-time
                    type: string
                  progress:
                    description: The progress in percentage (0-100) of the last operation.
                    format: int32
                    type: integer
                  state:
                    description: Status of the last operation, one of Aborted, Processing,
                      Succeeded, Error, Failed.
                    type: string
                  type:
                    description: Type of the last operation, one of Create, Reconcile,
                      Delete, Migrate, Restore.
                    type: string
                required:
                - description
                - lastUpdateTime
                - progress
                - state
                - type
                type: object
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  for this BackupBucket. It corresponds to the BackupBucket's generation,
                  which is updated on mutation by the API Server.
                format: int64
                type: integer
              providerStatus:
                description: ProviderStatus is the configuration passed to BackupBucket
                  resource.
                type: object
            type: object
        required:
        - metadata
        - spec
        - status
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1beta1
