apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: controllerdeployments.core.gardener.cloud
spec:
  conversion:
    strategy: None
  group: core.gardener.cloud
  names:
    categories:
    - all
    kind: ControllerDeployment
    listKind: ControllerDeploymentList
    plural: controllerdeployments
    shortNames:
    - ctrldeploy
    singular: controllerdeployment
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ControllerDeployment contains information about how this controller
          is deployed.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          helm:
            description: Helm configures that an extension controller is deployed
              using helm.
            properties:
              ociRepository:
                description: OCIRepository defines where to pull the chart.
                properties:
                  digest:
                    description: Digest of the image to pull, takes precedence over
                      tag. The value should be in the format 'sha256:<HASH>'.
                    type: string
                  pullSecretRef:
                    description: PullSecretRef is a reference to a secret containing
                      the pull secret. The secret must be of type `kubernetes.io/dockerconfigjson`
                      and must be located in the `garden` namespace. For usage in
                      the gardenlet, the secret must have the label `gardener.cloud/role=helm-pull-secret`.
                    properties:
                      name:
                        description: 'Name of the referent. This field is effectively
                          required, but due to backwards compatibility is allowed
                          to be empty. Instances of this type with an empty value
                          here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                        type: string
                    type: object
                  ref:
                    description: Ref is the full artifact Ref and takes precedence
                      over all other fields.
                    type: string
                  repository:
                    description: Repository is a reference to an OCI artifact repository.
                    type: string
                  tag:
                    description: Tag is the image tag to pull.
                    type: string
                type: object
              rawChart:
                description: RawChart is the base64-encoded, gzip'ed, tar'ed extension
                  controller chart.
                format: byte
                type: string
              values:
                description: Values are the chart values.
                x-kubernetes-preserve-unknown-fields: true
            type: object
          injectGardenKubeconfig:
            description: InjectGardenKubeconfig controls whether a kubeconfig to the
              garden cluster should be injected into workload resources.
            type: boolean
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1
