apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: meteringreports.metering.gardener.cloud
spec:
  conversion:
    strategy: None
  group: metering.gardener.cloud
  names:
    kind: MeteringReport
    listKind: MeteringReportList
    plural: meteringreports
    singular: meteringreport
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MeteringReport is a report that defines usage of a certain period
          of time.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MeteringReportSpec is the spec of the MeteringReport
            properties:
              objectRef:
                description: ObjectReference is a reference to a shoot object.
                properties:
                  apiGroup:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  project:
                    type: string
                  projectOwner:
                    type: string
                  uid:
                    type: string
                required:
                - apiGroup
                - kind
                - name
                - project
                - projectOwner
                - uid
                type: object
            required:
            - objectRef
            type: object
          status:
            description: MeteringReportStatus is the status of the metering report.
            properties:
              measurements:
                items:
                  description: Measurement describe all usages for any number of billing
                    periods.
                  properties:
                    billingPeriodRef:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    projectedUsage:
                      items:
                        description: Usage describes the usage
                        properties:
                          lastUpdated:
                            format: date-time
                            type: string
                          sku:
                            type: string
                          unit:
                            type: string
                          value:
                            format: double
                            type: number
                        required:
                        - lastUpdated
                        - sku
                        - unit
                        - value
                        type: object
                      type: array
                    usage:
                      items:
                        description: Usage describes the usage
                        properties:
                          lastUpdated:
                            format: date-time
                            type: string
                          sku:
                            type: string
                          unit:
                            type: string
                          value:
                            format: double
                            type: number
                        required:
                        - lastUpdated
                        - sku
                        - unit
                        - value
                        type: object
                      type: array
                  required:
                  - billingPeriodRef
                  - usage
                  type: object
                type: array
            required:
            - measurements
            type: object
        required:
        - spec
        - status
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1alpha1
